import { Label } from './label.models';
import { References } from './references.models';
import { TimeStats } from './time-stats.models';
import { Author } from './author.models';

export interface MergeRequest {
  id: number;
  iid: number;
  project_id: number;
  title: string;
  description: string;
  state: string;
  created_at: string;
  updated_at: string;
  target_branch: string;
  source_branch: string;
  upvotes: number;
  downvotes: number;
  author: Author;
  assignee?: any;
  source_project_id: number;
  target_project_id: number;
  closed_at?: any;
  closed_by?: any;
  labels: Label[];
  work_in_progress: boolean;
  milestone?: any;
  merge_when_pipeline_succeeds: boolean;
  merge_status: string;
  sha: string;
  merge_commit_sha?: any;
  squash_commit_sha?: any;
  user_notes_count: number;
  should_remove_source_branch?: any;
  force_remove_source_branch: boolean;
  web_url: string;
  reference: string;
  references: References;
  time_stats: TimeStats;
}
